# Generated by Django 4.2.10 on 2024-02-12 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_alter_article_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Views",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("count", models.TextField()),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_views",
                        to="articles.article",
                    ),
                ),
            ],
        ),
    ]
