# Generated by Django 4.2.10 on 2024-02-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0006_view_delete_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="view",
            name="count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="view",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
